version: '3.8'
services:
  app:
    image: nglzzz/twitch-bot:latest
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    restart: unless-stopped
    container_name: nglzzz_twitch_bot.app
    env_file: .env
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - ${DOCKER_WEB_PORT:-80}:${WEB_PORT:-8080}
      - ${DOCKER_WEBSOCKET_PORT:-81}:${WEBSOCKET_PORT:-8081}
    networks:
      - nglzzz_twitch_bot

#  db:
#    image: mongo:4.4.3-bionic
#    container_name: db
#    restart: unless-stopped
#    env_file: .env
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-root}
#      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-root}
#    volumes:
#      - dbdata:/data/db
#    networks:
#      - nglzzz_twitch_bot

networks:
  nglzzz_twitch_bot:
    name: nglzzz_twitch_bot
    driver: bridge

volumes:
  node_modules:
  dbdata:
